"use strict";

export const ORDER_ERROR_CODE = Object.freeze({
  ROLE_DENIED: "ROLE_DENIED",
  KILL_SWITCH: "KILL_SWITCH",
  DAILY_LOSS_LIMIT: "DAILY_LOSS_LIMIT",
  ORDER_NOTIONAL_LIMIT: "ORDER_NOTIONAL_LIMIT",
  POSITION_LIMIT: "POSITION_LIMIT",
  INSUFFICIENT_CASH: "INSUFFICIENT_CASH",
  INSUFFICIENT_POSITION: "INSUFFICIENT_POSITION",
  INVALID_SIDE: "INVALID_SIDE",
  INVALID_QTY: "INVALID_QTY",
  INVALID_PRICE: "INVALID_PRICE",
  INVALID_SYMBOL: "INVALID_SYMBOL",
  DUPLICATE_ORDER: "DUPLICATE_ORDER",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  BROKER_REJECTED: "BROKER_REJECTED",
  VALIDATION_REJECTED: "VALIDATION_REJECTED",
  RISK_REJECTED: "RISK_REJECTED",
});

export class OrderError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "OrderError";
    this.code = code;
  }
}
